services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: battle_hamsters
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
